package cloud.commands;

public enum Command {
    CREATE_FILE, DELETE_FILE, DIRECTORY_BACK, DIRECTORY_ONWARD, REFRESH,
    SAVE_FILE, SEND_FILE, SERVER_DIRECTORY, READY_TO_SEND, WRONG_FILE,
    READY_TO_SAVE, IS_EMPTY
}
